### ISSUE TITLE
Consider a more idiomatic set printer

### ISSUE THREAD

**Issue by dieggsy** [ThatGeoGuy/srfi-113#1]
As discussed on IRC, I do believe it's useful to have a record printer for sets, but the `&[ 1 2 3 ]` syntax feels like a different language (and was meant for debugging purposes).

I think it'd be nice to have some read syntax as well, but it's unclear to me how that should work given that sets require a comparator as input.

**Comment by ThatGeoGuy** [comment]
Alright, it's been a while since this was opened, and I apologize for the delay. 

I have the following working in a local build: 

```
CHICKEN
(c) 2008-2020, The CHICKEN Team
(c) 2000-2007, Felix L. Winkelmann
Version 5.2.0 (rev 317468e4)
linux-unix-gnu-x86-64 [ 64bit dload ptables ]

Type ,? for help.
; loading /home/jeremy/.csirc ...
; loading /var/lib//chicken/11/chicken.load.import.so ...
#;1> (import srfi-113)
; loading /var/lib//chicken/11/srfi-113.import.so ...
; loading /var/lib//chicken/11/srfi-113.so ...
; loading /var/lib//chicken/11/srfi-128.so ...
#;2> (set-union #s(1 4 5) #s(4 5 6))
#s(6 5 4 1)
#;3> (define my-bag #b(1 1 #\a #\a 2 3 4))
#;4> my-bag
#b(a a 4 3 2 1 1)
#;5>
```

The main gist is that `#b( ... )` and `#s( ... )` are used to denote bags and sets, respectively. The sharp syntax is a bit more idiomatic (IMO), but there's still a remaining problem: comparators in the read syntax.

So far this just uses the `make-default-comparator` procedure from SRFI-128. The default comparator would mostly be fine, but I'm yet unsure how one might update the "default" comparator if `(comparator-register-default! my-comparator)` is called. One idea is parameterization:

```scheme
(import srfi-113)

(comparator-register-default! my-comparator)
(parameterize ((sob-default-comparator (make-default-comparator))
  #s(1 2 3 4 5))
``` 

This isn't a horrible way to do things, and seems to work when I implement it:

```
#;6> (parameterize ((sob-default-comparator (make-eq-comparator))) #s((1 2) (1 2) 1 2))
#s((1 2) 2 1)
#;7>
```

Thoughts? Feedback? I don't know if `sob-default-comparator` is the best name for this, maybe it should be `sob-read-syntax-default-comparator`? Either way, it gets long. 

See the implementation in PR #2, if you want to build this locally yourself. In the meantime, I'm going to bump versions, ask for feedback on IRC, and get this ready to ship.

**Comment by johnwcowan** [comment]
It's messy, because #b means a binary number follows, so you have to do more backtracking.  If Chicken hadn't stolen braces, we could use those.

**Comment by dieggsy** [comment]
You can also give a symbol to set-sharp-read-syntax, but then you have to write e.g. `#!bag(1 2 3)`

**Comment by ThatGeoGuy** [comment]
Indeed, good points here, as well as the discussion on IRC.

Instead of parameters, I've applied a fixup: 174be0256d3c38ac72c9a3e11073cd185d10980f

This changes `#b` to `#!bag` to not conflict with binary numbers, as well as adds a `set-read-syntax-comparator!` for setting the comparator for read-syntax, instead of using parameters.

**Comment by lassik** [comment]
Late to the party...

Clojure uses `#{1 2 3}` for sets. That's the major precedent in the Lisp world.

`#set(1 2 3)` and `#bag(1 1 2 2 3 3)` would be the best ones for Scheme IMHO. That matches the `#u8(...)` and `#vu8(...)` read syntax for vectors.

@johnwcowan is right that `#b` presents a parsing conundrum, but to ensure sane future extensibility for Lisp family syntaxes, we need to permit `#any-letters-and-dashes-here`.

`#!` is more idiomatic for denoting some kind of meta-level thing than a Scheme object, though some implementations are using it for objects.

Surveys:

* https://registry.scheme.org/#hash-syntax
* https://registry.scheme.org/#hash-bang-syntax

**Comment by ThatGeoGuy** [comment]
Indeed. I was aware of how Clojure did sets, but I opted not to do that here since the issue is titled "Consider a more **idiomatic** set printer." Given that Clojure doesn't really have a notion of "comparators," and does equality [very differently than Scheme](https://clojure.org/guides/equality). However, I did avoid comparators here in the read-syntax, so I could see an argument for trying to be Clojure-like here.

I will admit `#bag(1 2 3)` is a bit better than `#!bag(1 2 3)`, but in the end I didn't plan to submit this to the SRFI upstream, and instead kept it CHICKEN only. In addition to that, CHICKEN's `set-sharp-read-syntax!` unfortunately forces the `#!<symbol>` over `#<symbol>`. I will admit that I'm not great with reader syntax in Scheme, and has been something I've largely avoided, mostly due to the fact that I actually prefer the `(set <comparator> . <rest>)` notation in my source code, rather than quoting literals.

The approach of keeping this syntax CHICKEN only may seem limiting (and folks are welcome to ask me to upstream this), but I felt that in most scenarios outside the REPL it makes more sense to use `(set <comparator> . <rest>)` over read syntax. I've closed the issue for now since I merged the existing work into SRFI 113, but others are more than welcome to keep discussion open. 

Of course, if the community feels like an alternative syntax to what's been done is preferable, then I'm happy to make the change. Given that the syntax is external to the SRFI itself and CHICKEN only, it shouldn't prevent anyone from writing portable code unless they really want to. @lassik thank you for chiming in, albeit late. If you feel strongly that a change is needed, I'm happy to have the discussion. You can find me as `DeeEff` on Libera.chat.
